export interface AemCoverageGapSeed {
  topic: string;
  category: string;
  topicGroup: string;
  profileTopic: string;
  relatedTopics: string[];
  question: string;
}

interface AemCoverageGapTopic {
  topic: string;
  category: string;
  topicGroup: string;
  profileTopic: string;
  relatedTopics: string[];
  gaps: string[];
}

const developmentGaps: AemCoverageGapTopic[] = [
  {
    topic: 'JCR',
    category: 'JCR',
    topicGroup: 'Fundamentals',
    profileTopic: 'JCR',
    relatedTopics: ['jcr', 'query-builder', 'security'],
    gaps: [
      'custom node types, primary types, and mixins without creating upgrade risk',
      'JCR versioning, restore behavior, and version-storage growth',
      'observation listeners that remain safe under clustered or cloud topology',
      'repository design for high-volume structured content',
      'Oak indexes, query plans, and traversal prevention',
      'concurrent writes, sessions, save boundaries, and conflict handling',
      'referential integrity, weak references, and content deletion',
      'ACL evaluation and permission-sensitive repository access',
      'repository growth, maintenance, and production performance diagnosis',
      'content packages, filters, and safe repository deployment',
      'workspaces and why AEM implementations rarely depend on multiple workspaces',
      'same-name siblings and content structures that avoid them',
      'locking, checkout behavior, and concurrent editorial updates',
      'namespaces and stable repository contracts',
      'binary properties, large values, and when content belongs in DAM',
      'session lifecycle, stale state, refresh, and transient changes',
      'repository corruption symptoms, evidence preservation, and escalation',
    ],
  },
  {
    topic: 'CRXDE',
    category: 'CRXDE',
    topicGroup: 'Fundamentals',
    profileTopic: 'JCR',
    relatedTopics: ['crxde', 'jcr', 'cloud-service'],
    gaps: [
      'comparing repository structures across environments without manual production edits',
      'inspecting node types, mixins, permissions, and effective policies',
      'diagnosing overlays and resource-supertype resolution',
      'using query and repository inspection tools safely during incidents',
      'turning a CRXDE discovery into a tested code or content-package fix',
    ],
  },
  {
    topic: 'Components',
    category: 'Components',
    topicGroup: 'Development',
    profileTopic: 'Components',
    relatedTopics: ['components', 'sling-models', 'editable-templates'],
    gaps: [
      'designing dialogs that remain usable and governable for enterprise authors',
      'choosing between configuration, policy, content, and code for component behavior',
      'extending Core Components through delegation without copying implementation',
      'versioning component contracts without breaking existing pages',
      'building component variants that remain reusable across brands',
      'preventing expensive rendering, queries, and integrations inside components',
      'designing accessible author-configurable markup',
      'integrating analytics and data-layer contracts consistently',
      'handling responsive behavior and asset delivery',
      'testing dialogs, Sling Models, HTL output, and authoring behavior',
      'diagnosing broken components after deployment or content migration',
      'designing multifield and composite-field storage that remains maintainable',
      'handling backward-compatible dialog and content-property changes',
      'using resource supertype and delegation without fragile inheritance chains',
      'designing component authoring validation and useful empty states',
      'supporting localization and right-to-left presentation requirements',
      'controlling component availability through templates and policies',
      'designing components for headless export and page rendering',
      'defining ownership and lifecycle for shared components',
      'measuring component adoption, defects, and rendering cost',
    ],
  },
  {
    topic: 'HTL',
    category: 'HTL',
    topicGroup: 'Development',
    profileTopic: 'Sling Models',
    relatedTopics: ['htl', 'sling-models', 'security'],
    gaps: [
      'selecting the correct display context for URLs, scripts, styles, and attributes',
      'using templates and calls for reusable markup without hiding complexity',
      'comparing Java Use API, JavaScript Use API, and Sling Models',
      'rendering dynamic attributes and data attributes safely',
      'preventing unsafe output when disabling or overriding escaping',
      'keeping HTL templates performant on heavily cached and uncached pages',
      'diagnosing expression, use-object, and rendering failures on Publish',
      'maintaining clean HTML semantics, accessibility, and testability',
      'using data-sly-resource and data-sly-include without creating hidden rendering cost',
      'understanding expression-language operators, collections, and null behavior',
      'using sly elements without producing invalid or inaccessible markup',
      'passing parameters to templates and use objects safely',
      'rendering URLs and selectors without introducing injection or cache problems',
      'testing HTL output and escaping behavior',
      'migrating JSP-based components to HTL',
    ],
  },
  {
    topic: 'Sling',
    category: 'Sling',
    topicGroup: 'Development',
    profileTopic: 'Sling Models',
    relatedTopics: ['sling', 'resource-resolver', 'dispatcher'],
    gaps: [
      'servlet resolution precedence across resource types, selectors, extensions, and methods',
      'resource mapping, vanity paths, aliases, and external URL generation',
      'request processing filters and avoiding excessive filter scope',
      'resource-merger overlays and safe product customization',
      'event handling and jobs without topology assumptions',
      'request progress tracking for difficult resolution failures',
      'resource-provider boundaries and non-JCR resources',
      'securing request parameters, selectors, suffixes, and custom endpoints',
    ],
  },
  {
    topic: 'AdaptTo Pattern',
    category: 'AdaptTo Pattern',
    topicGroup: 'Development',
    profileTopic: 'Sling Models',
    relatedTopics: ['adaptto-pattern', 'sling-models', 'resource-resolver'],
    gaps: [
      'distinguishing an unsupported adaptation from a permission or content failure',
      'designing custom AdapterFactory implementations and service ranking',
      'avoiding repeated adaptation and hidden work in rendering paths',
      'testing adapter contracts and null behavior',
      'using adaptable contracts without coupling services to request objects',
    ],
  },
  {
    topic: 'Client Libraries',
    category: 'Client Libraries',
    topicGroup: 'Development',
    profileTopic: 'Performance',
    relatedTopics: ['client-libraries', 'performance', 'components'],
    gaps: [
      'embed versus dependencies and preventing duplicate browser payloads',
      'allowProxy, public delivery, and Dispatcher filter requirements',
      'CSS and JavaScript processor configuration and minification failures',
      'loading critical, deferred, and page-specific assets',
      'debugging category resolution and ordering conflicts',
      'integrating modern frontend builds without losing AEM governance',
      'controlling third-party scripts for performance, privacy, and security',
    ],
  },
  {
    topic: 'Editable Templates',
    category: 'Editable Templates',
    topicGroup: 'Content Management',
    profileTopic: 'Templates',
    relatedTopics: ['editable-templates', 'content-policies', 'components'],
    gaps: [
      'governing template-editor permissions and ownership',
      'changing locked structure without damaging existing pages',
      'managing responsive-grid and allowed-component behavior',
      'using template types across multiple sites and brands',
      'debugging policy mappings and broken template references',
      'migrating static-template sites to editable templates',
      'testing template and policy changes before rollout',
    ],
  },
  {
    topic: 'Templates',
    category: 'Templates',
    topicGroup: 'Content Management',
    profileTopic: 'Templates',
    relatedTopics: ['templates', 'editable-templates', 'content-policies'],
    gaps: [
      'choosing static templates, editable templates, and template types during modernization',
      'designing template structure, initial content, and author freedom',
      'governing allowed components and responsive layout behavior',
      'sharing templates across sites without coupling brand ownership',
      'versioning template changes without breaking existing pages',
      'promoting template definitions, policies, and configuration safely',
      'diagnosing pages that resolve the wrong template or policy',
      'migrating legacy page structures onto governed templates',
      'handling template availability and allowedPaths across site roots',
      'designing template governance for page creation and retirement',
      'testing template changes against inherited and localized pages',
      'recovering from template changes that break page rendering',
    ],
  },
  {
    topic: 'Content Policies',
    category: 'Content Policies',
    topicGroup: 'Content Management',
    profileTopic: 'Templates',
    relatedTopics: ['content-policies', 'editable-templates', 'components'],
    gaps: [
      'separating author choices from centrally governed design decisions',
      'using policy mappings with inherited and nested components',
      'versioning policy changes across shared templates',
      'diagnosing policy resolution through content and configuration paths',
      'designing brand-specific variation without component forks',
      'testing policy changes against existing authored content',
      'recovering from missing or incorrectly promoted policies',
    ],
  },
  {
    topic: 'Experience Fragments',
    category: 'Experience Fragments',
    topicGroup: 'Content Management',
    profileTopic: 'Content Fragments',
    relatedTopics: ['experience-fragments', 'msm', 'dispatcher'],
    gaps: [
      'choosing Experience Fragments versus components, pages, and Content Fragments',
      'designing variations for channels, brands, and locales',
      'governing editable templates and policies used by fragments',
      'publishing referenced assets and avoiding stale delivery',
      'using MSM and translation without losing local ownership',
      'integrating Experience Fragments with external delivery channels',
      'controlling cache invalidation when fragments are referenced broadly',
      'diagnosing broken fragment references after moves or migration',
    ],
  },
  {
    topic: 'Service Users',
    category: 'Service Users',
    topicGroup: 'Advanced',
    profileTopic: 'Security',
    relatedTopics: ['service-users', 'resource-resolver', 'security'],
    gaps: [
      'designing subservice names and mappings for independently owned capabilities',
      'creating repoinit-managed users and ACLs through code',
      'reviewing effective permissions and preventing privilege creep',
      'separating read, write, and administrative responsibilities',
      'testing service-user behavior in local, stage, and production-like environments',
      'diagnosing authentication versus authorization failures',
      'migrating legacy admin-session code safely',
    ],
  },
  {
    topic: 'Resource Resolver',
    category: 'Resource Resolver',
    topicGroup: 'Advanced',
    profileTopic: 'Security',
    relatedTopics: ['resource-resolver', 'service-users', 'security'],
    gaps: [
      'choosing request-bound, service, and administrative resolver patterns',
      'closing resolvers safely and detecting resolver leaks',
      'mapping resource paths, aliases, and externalized URLs',
      'distinguishing missing resources from denied repository access',
      'handling writes, commits, refreshes, and concurrent changes',
      'testing resolver behavior under least-privilege service users',
      'diagnosing environment-specific service-user mapping failures',
      'using resolver mapping and externalization without generating incorrect public URLs',
      'avoiding long-lived resolvers in schedulers, jobs, and services',
      'measuring and troubleshooting resolver-related repository pressure',
    ],
  },
];

const contentAndOperationsGaps: AemCoverageGapTopic[] = [
  {
    topic: 'MSM',
    category: 'MSM',
    topicGroup: 'Content Management',
    profileTopic: 'Architecture',
    relatedTopics: ['msm', 'translation', 'multi-site-manager'],
    gaps: [
      'designing custom rollout actions and avoiding unintended content changes',
      'moving and renaming blueprint content without breaking live copies',
      'managing component-level inheritance and local exceptions',
      'measuring rollout health across a large site estate',
      'combining MSM with reusable fragments and shared assets',
      'migrating or restructuring an established MSM implementation',
    ],
  },
  {
    topic: 'Workflows',
    category: 'Workflows',
    topicGroup: 'Content Management',
    profileTopic: 'OSGi',
    relatedTopics: ['workflows', 'launches', 'production-support'],
    gaps: [
      'selecting transient versus persisted workflows',
      'designing participant steps, dynamic participants, and escalation',
      'controlling payload size and batch-processing impact',
      'using workflow metadata without coupling process steps',
      'securing workflow execution and participant access',
      'cleaning completed instances and diagnosing repository growth',
    ],
  },
  {
    topic: 'Query Builder',
    category: 'Query Builder',
    topicGroup: 'Advanced',
    profileTopic: 'JCR',
    relatedTopics: ['query-builder', 'jcr', 'performance'],
    gaps: [
      'choosing Query Builder versus JCR SQL2 and direct repository navigation',
      'using facets, groups, ordering, and multiple predicates efficiently',
      'handling guessTotal, result limits, and large result sets',
      'creating custom predicates without hiding traversal',
      'testing queries with realistic production content volumes',
      'monitoring query regressions after model or index changes',
    ],
  },
  {
    topic: 'Replication',
    category: 'Replication',
    topicGroup: 'Production Support',
    profileTopic: 'AEM Cloud Service',
    relatedTopics: ['replication', 'dispatcher', 'production-support'],
    gaps: [
      'distinguishing activation, deactivation, deletion, and tree activation behavior',
      'designing publication permissions and approval controls',
      'diagnosing queue retries, blocked agents, and receiver failures',
      'handling aliases, redirects, and moved content during publication',
      'validating cache invalidation after publication',
      'operating publication safely during high-volume releases',
      'comparing traditional replication with Cloud Service publication',
    ],
  },
  {
    topic: 'Launches',
    category: 'Launches',
    topicGroup: 'Content Management',
    profileTopic: 'Templates',
    relatedTopics: ['launches', 'workflows', 'content-governance'],
    gaps: [
      'handling nested launches and inherited source changes',
      'promoting only approved changes from a launch',
      'resolving conflicts between live and launch content',
      'testing launch promotion with referenced fragments and assets',
      'cleaning abandoned launches and controlling repository growth',
      'choosing launches versus MSM, workflows, and scheduled publication',
    ],
  },
  {
    topic: 'Translation',
    category: 'Translation',
    topicGroup: 'Content Management',
    profileTopic: 'Content Fragments',
    relatedTopics: ['translation', 'msm', 'content-fragments'],
    gaps: [
      'configuring translation rules for pages, fragments, and assets',
      'integrating translation providers and diagnosing connector failures',
      'handling source changes while a translation job is active',
      'protecting non-translatable fields and technical metadata',
      'measuring translation completeness before publication',
      'designing fallback behavior for missing locale content',
      'operating translations across multi-brand and multi-region programs',
    ],
  },
  {
    topic: 'DAM',
    category: 'DAM',
    topicGroup: 'Content Management',
    profileTopic: 'Content Fragments',
    relatedTopics: ['dam', 'assets', 'performance'],
    gaps: [
      'designing folder structure, metadata inheritance, and searchability',
      'governing asset expiry, rights, licensing, and compliance',
      'handling duplicate detection and asset-reference integrity',
      'designing review, approval, and publication workflows for assets',
      'planning bulk migration and metadata reconciliation',
      'diagnosing asset-processing backlogs and failed jobs',
      'securing confidential assets across authoring and delivery',
    ],
  },
  {
    topic: 'Assets',
    category: 'Assets',
    topicGroup: 'Content Management',
    profileTopic: 'Performance',
    relatedTopics: ['assets', 'dam', 'cdn'],
    gaps: [
      'choosing Dynamic Media, web-optimized delivery, and static renditions',
      'designing smart crops and responsive image behavior',
      'controlling asset publication and delivery permissions',
      'preserving metadata and references during asset moves',
      'measuring delivery performance and rendition quality',
      'handling asset replacement without stale CDN content',
      'testing components against missing, oversized, or unsupported assets',
    ],
  },
  {
    topic: 'Apache Configuration',
    category: 'Apache Configuration',
    topicGroup: 'Advanced',
    profileTopic: 'Dispatcher',
    relatedTopics: ['apache', 'dispatcher', 'security'],
    gaps: [
      'ordering rewrite rules, aliases, redirects, and Dispatcher handling',
      'designing HTTPS, host, and proxy-header behavior',
      'setting CSP, HSTS, and other security headers safely',
      'controlling compression, MIME types, and static asset caching',
      'debugging multi-domain vhost selection',
      'testing configuration changes before Cloud Manager deployment',
      'preventing open redirects and unsafe proxy behavior',
    ],
  },
  {
    topic: 'Dispatcher Caching',
    category: 'Dispatcher Caching',
    topicGroup: 'Advanced',
    profileTopic: 'Dispatcher',
    relatedTopics: ['dispatcher-caching', 'cdn', 'performance'],
    gaps: [
      'deciding which responses are safe and valuable to cache',
      'designing statfileslevel and invalidation boundaries for deep site structures',
      'handling query parameters, selectors, cookies, and cache variation',
      'invalidating pages that reference fragments, assets, and shared content',
      'preventing authenticated, personalized, and sensitive response caching',
      'diagnosing low cache-hit ratio and unexpected cache misses',
      'coordinating Dispatcher and CDN freshness without duplicate rules',
      'handling cache files, headers, and invalidation safely during blue-green releases',
    ],
  },
  {
    topic: 'CDN',
    category: 'CDN',
    topicGroup: 'Advanced',
    profileTopic: 'Dispatcher',
    relatedTopics: ['cdn', 'dispatcher', 'performance'],
    gaps: [
      'designing surrogate keys or invalidation strategies for shared content',
      'controlling cache variation by headers, cookies, query parameters, and locale',
      'preventing origin overload during cache misses or invalidation events',
      'handling redirects, errors, and negative caching',
      'protecting authenticated and personalized responses',
      'using edge rules without duplicating application behavior',
      'diagnosing regional CDN issues and proving origin health',
    ],
  },
  {
    topic: 'Accessibility',
    category: 'Accessibility',
    topicGroup: 'Development',
    profileTopic: 'Components',
    relatedTopics: ['accessibility', 'components', 'testing'],
    gaps: [
      'designing dialog validation that guides authors toward accessible content',
      'handling heading hierarchy and landmark structure across editable pages',
      'building accessible interactive components and focus management',
      'managing alt text, decorative images, and DAM metadata',
      'testing color contrast and brand-configurable themes',
      'automating accessibility checks without relying on automation alone',
      'triaging accessibility regressions in shared components',
    ],
  },
  {
    topic: 'Testing',
    category: 'Testing',
    topicGroup: 'Development',
    profileTopic: 'Cloud Manager',
    relatedTopics: ['testing', 'cloud-manager', 'components'],
    gaps: [
      'using AEM Mocks for repository, request, and model tests',
      'testing workflow steps, schedulers, jobs, and event handlers',
      'testing permission-sensitive and service-user behavior',
      'designing contract tests for external integrations',
      'building performance and load-test scenarios',
      'maintaining stable UI and authoring tests',
      'testing migration transformations and content reconciliation',
    ],
  },
  {
    topic: 'Production Support',
    category: 'Production Support',
    topicGroup: 'Production Support',
    profileTopic: 'Performance',
    relatedTopics: ['production-support', 'monitoring', 'troubleshooting'],
    gaps: [
      'classifying severity, business impact, and incident ownership',
      'preserving evidence before mitigation',
      'communicating status and decisions during a major incident',
      'using rollback, forward-fix, feature flags, and graceful degradation',
      'handling repeated incidents through problem management',
      'building on-call handover, runbooks, and escalation paths',
      'conducting blameless post-incident review and tracking prevention work',
    ],
  },
  {
    topic: 'Troubleshooting',
    category: 'Troubleshooting',
    topicGroup: 'Production Support',
    profileTopic: 'Performance',
    relatedTopics: ['troubleshooting', 'logging', 'monitoring'],
    gaps: [
      'forming and testing hypotheses instead of applying broad fixes',
      'diagnosing intermittent issues with correlation IDs and timelines',
      'separating code, configuration, content, permission, and infrastructure failures',
      'reproducing production behavior safely with representative data',
      'using thread dumps, logs, metrics, and request traces together',
      'validating remediation, rollback criteria, and recurrence prevention',
      'communicating technical findings to business and support stakeholders',
    ],
  },
  {
    topic: 'Monitoring',
    category: 'Monitoring',
    topicGroup: 'Production Support',
    profileTopic: 'Performance',
    relatedTopics: ['monitoring', 'logging', 'cloud-manager'],
    gaps: [
      'defining SLIs, SLOs, and error budgets for AEM journeys',
      'monitoring Author experience and publication latency',
      'tracking query, workflow, asset-processing, and integration health',
      'building dashboards that connect technical signals to user impact',
      'designing alert thresholds, escalation, and ownership',
      'using synthetic monitoring for critical journeys',
      'validating monitoring coverage during releases and migrations',
    ],
  },
  {
    topic: 'Logging',
    category: 'Logging',
    topicGroup: 'Production Support',
    profileTopic: 'AEM Cloud Service',
    relatedTopics: ['logging', 'monitoring', 'security'],
    gaps: [
      'selecting logger names and levels without flooding production',
      'adding correlation and business context to diagnostic logs',
      'logging integration failures while protecting customer data',
      'creating actionable log-based alerts',
      'diagnosing issues across Author, Publish, Dispatcher, and CDN logs',
      'retaining evidence for audit and incident review',
      'reducing noisy repeated errors and logging cost',
    ],
  },
];

const architectureAndGovernanceGaps: AemCoverageGapTopic[] = [
  {
    topic: 'SEO in AEM',
    category: 'SEO in AEM',
    topicGroup: 'Development',
    profileTopic: 'Components',
    relatedTopics: ['seo', 'components', 'multi-site'],
    gaps: [
      'designing metadata inheritance and author overrides',
      'handling hreflang and regional-domain relationships',
      'preventing accidental noindex, canonical, and robots regressions',
      'managing redirect inventories during migrations',
      'rendering structured data with governed content contracts',
      'testing crawlability across Dispatcher, CDN, and client-rendered experiences',
      'monitoring SEO regressions after releases and content changes',
    ],
  },
  {
    topic: 'Headless AEM',
    category: 'Headless AEM',
    topicGroup: 'Architecture',
    profileTopic: 'GraphQL',
    relatedTopics: ['headless-aem', 'graphql', 'content-fragments'],
    gaps: [
      'choosing headless, traditional, and hybrid delivery by business capability',
      'designing preview, authoring, and editorial workflows for headless consumers',
      'versioning content models and consumer contracts',
      'handling authentication, authorization, and public delivery',
      'designing cache invalidation across multiple consuming applications',
      'operating headless delivery during schema and content migrations',
      'measuring API performance, availability, and consumer impact',
    ],
  },
  {
    topic: 'Integration Patterns',
    category: 'Integration Patterns',
    topicGroup: 'Architecture',
    profileTopic: 'OSGi',
    relatedTopics: ['integrations', 'osgi', 'architecture'],
    gaps: [
      'designing rate limits, backpressure, and bulkheads',
      'handling webhook security and duplicate delivery',
      'choosing event-driven integration versus scheduled synchronization',
      'maintaining consistency when AEM and external systems disagree',
      'testing degraded dependencies and recovery behavior',
      'planning API versioning and vendor replacement',
      'protecting Publish rendering from integration latency',
    ],
  },
  {
    topic: 'Multi Site Manager',
    category: 'Multi Site Manager',
    topicGroup: 'Architecture',
    profileTopic: 'Architecture',
    relatedTopics: ['multi-site-manager', 'msm', 'translation'],
    gaps: [
      'choosing site hierarchy and blueprint boundaries',
      'designing permissions and ownership across central and local teams',
      'handling regional legal, design, and content variation',
      'combining shared components, policies, fragments, and assets',
      'planning site creation, rollout, archival, and retirement',
      'measuring governance exceptions and local-market autonomy',
      'migrating independently built sites onto a shared platform',
    ],
  },
  {
    topic: 'Multi Brand Architecture',
    category: 'Multi Brand Architecture',
    topicGroup: 'Architecture',
    profileTopic: 'Architecture',
    relatedTopics: ['multi-brand', 'components', 'governance'],
    gaps: [
      'designing brand inheritance for templates, policies, and design tokens',
      'separating brand release cadence from shared-platform releases',
      'handling brand-specific integrations and legal requirements',
      'governing component variants and preventing forks',
      'measuring reuse, adoption, and total cost of ownership',
      'onboarding and retiring brands without destabilizing the platform',
      'operating shared incidents with clear brand and platform ownership',
    ],
  },
  {
    topic: 'Multi Region Architecture',
    category: 'Multi Region Architecture',
    topicGroup: 'Architecture',
    profileTopic: 'Architecture',
    relatedTopics: ['multi-region', 'cdn', 'aem-cloud-service'],
    gaps: [
      'designing regional integration dependencies and failure isolation',
      'handling content embargoes and synchronized global launches',
      'planning regional performance tests and capacity assumptions',
      'governing privacy, consent, and data residency',
      'designing operational follow-the-sun support',
      'testing disaster recovery and regional dependency failure',
      'balancing regional autonomy with shared-platform governance',
    ],
  },
  {
    topic: 'Migration',
    category: 'Migration',
    topicGroup: 'Architecture',
    profileTopic: 'AEM Cloud Service',
    relatedTopics: ['migration', 'aem-cloud-service', 'governance'],
    gaps: [
      'building inventory, dependency maps, and migration waves',
      'designing transformation rules and exception handling',
      'reconciling source and target content after transfer',
      'migrating users, groups, permissions, and service access',
      'validating SEO, redirects, analytics, and integrations at cutover',
      'operating parallel change while migration is underway',
      'retiring legacy environments and support processes safely',
    ],
  },
  {
    topic: 'Migration Scenarios',
    category: 'Migration Scenarios',
    topicGroup: 'Architecture',
    profileTopic: 'AEM Cloud Service',
    relatedTopics: ['migration', 'aem-cloud-service', 'upgrade-projects'],
    gaps: [
      'migrating a multi-brand platform in independently releasable waves',
      'moving from static templates and legacy components to modern patterns',
      'migrating large DAM estates while preserving references and metadata',
      'handling late content changes during cutover',
      'recovering from incomplete transfer or validation failure',
      'planning business rehearsal and go-live decision criteria',
      'measuring post-migration stability, adoption, and technical debt',
    ],
  },
  {
    topic: 'Upgrade Projects',
    category: 'Upgrade Projects',
    topicGroup: 'Architecture',
    profileTopic: 'AEM Cloud Service',
    relatedTopics: ['upgrade', 'migration', 'testing'],
    gaps: [
      'inventorying custom code, overlays, dependencies, and deprecated APIs',
      'handling repository restructuring and index changes',
      'planning package, bundle, and third-party library compatibility',
      'validating authoring workflows and operational tooling',
      'designing phased rollout, rollback, and support readiness',
      'measuring performance and functional regressions',
      'using an upgrade to reduce technical debt without expanding risk',
    ],
  },
  {
    topic: 'Governance',
    category: 'Governance',
    topicGroup: 'Architecture',
    profileTopic: 'Architecture',
    relatedTopics: ['governance', 'security', 'multi-brand'],
    gaps: [
      'defining platform, product, content, and operations decision rights',
      'governing exceptions without blocking delivery',
      'creating standards for components, templates, models, and integrations',
      'measuring adoption, reuse, quality, performance, and cost',
      'managing architecture decisions and technical-debt portfolios',
      'governing vendors, partners, and distributed delivery teams',
      'operating release, incident, security, and change governance together',
    ],
  },
];

const finalCoverageGaps: AemCoverageGapTopic[] = [
  {
    topic: 'Accessibility', category: 'Accessibility', topicGroup: 'Development', profileTopic: 'Components', relatedTopics: ['accessibility', 'components', 'testing'],
    gaps: ['embedding accessibility acceptance criteria into component delivery', 'handling accessible error messages and validation states', 'governing accessibility evidence for regulated releases'],
  },
  {
    topic: 'AdaptTo Pattern', category: 'AdaptTo Pattern', topicGroup: 'Development', profileTopic: 'Sling Models', relatedTopics: ['adaptto-pattern', 'sling-models', 'resource-resolver'],
    gaps: ['choosing adaptation versus explicit service APIs', 'debugging adapter-factory ordering and activation', 'documenting adapter preconditions for reusable APIs', 'monitoring adaptation failures that otherwise appear as null values'],
  },
  {
    topic: 'Apache Configuration', category: 'Apache Configuration', topicGroup: 'Advanced', profileTopic: 'Dispatcher', relatedTopics: ['apache', 'dispatcher', 'security'],
    gaps: ['operating maintenance pages and controlled traffic cutover', 'protecting origin addresses and trusted proxy behavior', 'diagnosing response-header differences between environments'],
  },
  {
    topic: 'Assets', category: 'Assets', topicGroup: 'Content Management', profileTopic: 'Performance', relatedTopics: ['assets', 'dam', 'cdn'],
    gaps: ['designing asset naming and folder conventions for authors', 'handling rights-managed assets after expiry', 'diagnosing broken asset references across published pages'],
  },
  {
    topic: 'CDN', category: 'CDN', topicGroup: 'Advanced', profileTopic: 'Dispatcher', relatedTopics: ['cdn', 'dispatcher', 'performance'],
    gaps: ['designing origin shielding and request-collapse behavior', 'operating emergency purge without causing an origin surge', 'validating security headers and redirects at the edge'],
  },
  {
    topic: 'CRXDE', category: 'CRXDE', topicGroup: 'Fundamentals', profileTopic: 'JCR', relatedTopics: ['crxde', 'jcr', 'cloud-service'],
    gaps: ['inspecting package-installed content and filter ownership', 'diagnosing repository permission inheritance', 'tracing component resolution from content to scripts', 'identifying configuration differences without changing runtime state', 'using repository inspection evidence in a production incident handoff'],
  },
  {
    topic: 'Client Libraries', category: 'Client Libraries', topicGroup: 'Development', profileTopic: 'Performance', relatedTopics: ['client-libraries', 'performance', 'components'],
    gaps: ['preventing client-library cache invalidation problems after deployment', 'testing client-library dependencies across templates and page types'],
  },
  {
    topic: 'Content Policies', category: 'Content Policies', topicGroup: 'Content Management', profileTopic: 'Templates', relatedTopics: ['content-policies', 'editable-templates', 'components'],
    gaps: ['auditing policy usage before deletion or consolidation', 'governing policy-editor permissions', 'migrating duplicated policies into a shared model'],
  },
  {
    topic: 'DAM', category: 'DAM', topicGroup: 'Content Management', profileTopic: 'Content Fragments', relatedTopics: ['dam', 'assets', 'performance'],
    gaps: ['measuring DAM adoption, search quality, and operational health'],
  },
  {
    topic: 'Editable Templates', category: 'Editable Templates', topicGroup: 'Content Management', profileTopic: 'Templates', relatedTopics: ['editable-templates', 'content-policies', 'components'],
    gaps: ['supporting controlled template variation across locales', 'auditing template usage before structural changes'],
  },
  {
    topic: 'Experience Fragments', category: 'Experience Fragments', topicGroup: 'Content Management', profileTopic: 'Content Fragments', relatedTopics: ['experience-fragments', 'msm', 'dispatcher'],
    gaps: ['measuring fragment reuse and identifying duplicated experiences', 'retiring fragment variations without breaking consumers'],
  },
  {
    topic: 'Governance', category: 'Governance', topicGroup: 'Architecture', profileTopic: 'Architecture', relatedTopics: ['governance', 'security', 'multi-brand'],
    gaps: ['designing governance that scales from project delivery into platform operations'],
  },
  {
    topic: 'Headless AEM', category: 'Headless AEM', topicGroup: 'Architecture', profileTopic: 'GraphQL', relatedTopics: ['headless-aem', 'graphql', 'content-fragments'],
    gaps: ['designing consumer onboarding, documentation, and support ownership'],
  },
  {
    topic: 'Integration Patterns', category: 'Integration Patterns', topicGroup: 'Architecture', profileTopic: 'OSGi', relatedTopics: ['integrations', 'osgi', 'architecture'],
    gaps: ['designing reconciliation and audit trails for business-critical integrations'],
  },
  {
    topic: 'Launches', category: 'Launches', topicGroup: 'Content Management', profileTopic: 'Templates', relatedTopics: ['launches', 'workflows', 'content-governance'],
    gaps: ['managing permissions and ownership for confidential launch content', 'coordinating launch promotion with translation', 'diagnosing missing dependencies after launch promotion', 'reporting launch readiness before a campaign deadline'],
  },
  {
    topic: 'Logging', category: 'Logging', topicGroup: 'Production Support', profileTopic: 'AEM Cloud Service', relatedTopics: ['logging', 'monitoring', 'security'],
    gaps: ['choosing when to log, meter, trace, or alert', 'using temporary diagnostic logging safely in production', 'creating support-ready log messages for shared services'],
  },
  {
    topic: 'MSM', category: 'MSM', topicGroup: 'Content Management', profileTopic: 'Architecture', relatedTopics: ['msm', 'translation', 'multi-site-manager'],
    gaps: ['auditing inheritance state and local exceptions before a major rollout'],
  },
  {
    topic: 'Migration', category: 'Migration', topicGroup: 'Architecture', profileTopic: 'AEM Cloud Service', relatedTopics: ['migration', 'aem-cloud-service', 'governance'],
    gaps: ['building migration governance, decision rights, and acceptance criteria'],
  },
  {
    topic: 'Migration Scenarios', category: 'Migration Scenarios', topicGroup: 'Architecture', profileTopic: 'AEM Cloud Service', relatedTopics: ['migration', 'aem-cloud-service', 'upgrade-projects'],
    gaps: ['handling migration when source content quality is inconsistent', 'migrating while multiple feature teams continue releasing'],
  },
  {
    topic: 'Monitoring', category: 'Monitoring', topicGroup: 'Production Support', profileTopic: 'Performance', relatedTopics: ['monitoring', 'logging', 'cloud-manager'],
    gaps: ['monitoring cache effectiveness and origin protection', 'detecting slow degradation before a customer-visible outage', 'reviewing monitoring gaps after an incident'],
  },
  {
    topic: 'Multi Brand Architecture', category: 'Multi Brand Architecture', topicGroup: 'Architecture', profileTopic: 'Architecture', relatedTopics: ['multi-brand', 'components', 'governance'],
    gaps: ['designing brand onboarding standards and architecture fitness checks'],
  },
  {
    topic: 'Multi Region Architecture', category: 'Multi Region Architecture', topicGroup: 'Architecture', profileTopic: 'Architecture', relatedTopics: ['multi-region', 'cdn', 'aem-cloud-service'],
    gaps: ['designing global observability and region-aware incident response'],
  },
  {
    topic: 'Multi Site Manager', category: 'Multi Site Manager', topicGroup: 'Architecture', profileTopic: 'Architecture', relatedTopics: ['multi-site-manager', 'msm', 'translation'],
    gaps: ['designing repeatable site provisioning', 'governing shared navigation and cross-site references', 'measuring platform health across many sites'],
  },
  {
    topic: 'Production Support', category: 'Production Support', topicGroup: 'Production Support', profileTopic: 'Performance', relatedTopics: ['production-support', 'monitoring', 'troubleshooting'],
    gaps: ['defining operational readiness criteria before launch'],
  },
  {
    topic: 'Query Builder', category: 'Query Builder', topicGroup: 'Advanced', profileTopic: 'JCR', relatedTopics: ['query-builder', 'jcr', 'performance'],
    gaps: ['reviewing query ownership and performance budgets before release'],
  },
  {
    topic: 'Replication', category: 'Replication', topicGroup: 'Production Support', profileTopic: 'AEM Cloud Service', relatedTopics: ['replication', 'dispatcher', 'production-support'],
    gaps: ['monitoring publication latency and queue health', 'recovering safely after a large failed publication', 'validating publication across multi-site dependencies'],
  },
  {
    topic: 'SEO in AEM', category: 'SEO in AEM', topicGroup: 'Development', profileTopic: 'Components', relatedTopics: ['seo', 'components', 'multi-site'],
    gaps: ['handling pagination and faceted URLs without crawl waste', 'designing author-friendly SEO validation', 'coordinating SEO acceptance during platform migration'],
  },
  {
    topic: 'Service Users', category: 'Service Users', topicGroup: 'Advanced', profileTopic: 'Security', relatedTopics: ['service-users', 'security', 'resource-resolver'],
    gaps: ['auditing service-user usage across a large codebase', 'handling service-user ownership when teams change', 'detecting and responding to unexpected privileged access'],
  },
  {
    topic: 'Sling', category: 'Sling', topicGroup: 'Development', profileTopic: 'Sling Models', relatedTopics: ['sling', 'resource-resolver', 'dispatcher'],
    gaps: ['debugging script resolution and servlet selection with request-progress evidence', 'designing stable resource types across component versions'],
  },
  {
    topic: 'Testing', category: 'Testing', topicGroup: 'Development', profileTopic: 'Cloud Manager', relatedTopics: ['testing', 'cloud-manager', 'components'],
    gaps: ['using production defects to improve the automated test strategy'],
  },
  {
    topic: 'Translation', category: 'Translation', topicGroup: 'Content Management', profileTopic: 'Content Fragments', relatedTopics: ['translation', 'msm', 'content-fragments'],
    gaps: ['estimating translation scope and cost before launch', 'handling translation-memory and terminology governance', 'validating translated experiences across pages, fragments, and assets'],
  },
  {
    topic: 'Troubleshooting', category: 'Troubleshooting', topicGroup: 'Production Support', profileTopic: 'Performance', relatedTopics: ['troubleshooting', 'logging', 'monitoring'],
    gaps: ['deciding when to escalate to Adobe Support with a complete evidence package', 'distinguishing correlation from root cause during release incidents', 'building reusable diagnostic playbooks from solved issues'],
  },
  {
    topic: 'Upgrade Projects', category: 'Upgrade Projects', topicGroup: 'Architecture', profileTopic: 'AEM Cloud Service', relatedTopics: ['upgrade', 'migration', 'testing'],
    gaps: ['planning author and support-team readiness for upgraded behavior', 'handling upgrade blockers owned by external vendors', 'validating rollback feasibility before the upgrade window'],
  },
  {
    topic: 'Workflows', category: 'Workflows', topicGroup: 'Content Management', profileTopic: 'OSGi', relatedTopics: ['workflows', 'launches', 'production-support'],
    gaps: ['governing workflow-model changes while instances are already running'],
  },
];

function expandGap(topic: AemCoverageGapTopic, gap: string): AemCoverageGapSeed {
  return {
    topic: topic.topic,
    category: topic.category,
    topicGroup: topic.topicGroup,
    profileTopic: topic.profileTopic,
    relatedTopics: topic.relatedTopics,
    question: `How would you approach ${gap} in ${topic.topic}? Include operational constraints, diagnostic evidence, and enterprise trade-offs.`,
  };
}

export const aemCoverageGapQuestionSeeds: AemCoverageGapSeed[] = [
  ...developmentGaps,
  ...contentAndOperationsGaps,
  ...architectureAndGovernanceGaps,
  ...finalCoverageGaps,
].flatMap((topic) => topic.gaps.map((gap) => expandGap(topic, gap)));
