export interface AemEnterpriseExpansionTopic {
  topic: string;
  category: string;
  topicGroup: string;
  profileTopic: string;
  relatedTopics: string[];
  concerns: string[];
}

export interface AemEnterpriseQuestionSeed {
  topic: string;
  category: string;
  topicGroup: string;
  profileTopic: string;
  relatedTopics: string[];
  question: string;
}

const coreExpansionTopics: AemEnterpriseExpansionTopic[] = [
  {
    topic: 'Architecture',
    category: 'AEM Architecture',
    topicGroup: 'Architecture',
    profileTopic: 'Architecture',
    relatedTopics: ['dispatcher', 'aem-cloud-service', 'governance'],
    concerns: [
      'isolating public marketing traffic from authenticated customer journeys',
      'supporting multiple brands without cloning codebases',
      'supporting regional sites with data residency and latency requirements',
      'designing graceful degradation when an external personalization service fails',
      'separating content ownership from application and environment configuration',
      'planning blue-green or low-risk releases for business-critical journeys',
      'designing active-active delivery expectations across regions',
      'governing shared components, templates, and policies across business units',
      'integrating AEM with commerce, PIM, CRM, and analytics platforms',
      'preventing Author, Publish, Dispatcher, and CDN responsibilities from overlapping',
      'designing observability across content publication and request delivery',
      'planning high-traffic campaign launches without overloading Publish',
      'deciding between page delivery, headless delivery, and hybrid architecture',
      'designing disaster recovery and business continuity expectations',
      'controlling privileged operational access and emergency changes',
      'planning content migrations while feature teams continue development',
      'reducing blast radius between unrelated sites and programs',
      'designing reusable content models for web, mobile, and partner channels',
      'balancing platform standardization with local-market autonomy',
      'establishing architecture decision records and technical governance',
    ],
  },
  {
    topic: 'Dispatcher',
    category: 'Dispatcher',
    topicGroup: 'Advanced',
    profileTopic: 'Dispatcher',
    relatedTopics: ['dispatcher', 'cdn', 'security'],
    concerns: [
      'deny-by-default filters for a site with custom servlets and GraphQL endpoints',
      'cache invalidation across multiple domains and Dispatcher farms',
      'statfileslevel selection for deeply nested site structures',
      'query parameters that affect rendering and cache variants',
      'personalized pages mixed with cacheable anonymous content',
      'protecting Publish from authoring and internal endpoints',
      'vhost matching for live traffic and flush requests',
      'stale Experience Fragments and referenced assets after publication',
      'cache-control headers shared between Dispatcher and CDN',
      'safe caching of redirects, errors, and vanity URLs',
      'debugging intermittent cache misses during campaign traffic',
      'Dispatcher configuration promotion through Cloud Manager',
      'supporting multiple brands and domains without rule duplication',
      'preventing cache poisoning and sensitive response caching',
      'measuring cache-hit ratio and proving Dispatcher effectiveness',
    ],
  },
  {
    topic: 'OSGi',
    category: 'OSGi',
    topicGroup: 'Development',
    profileTopic: 'OSGi',
    relatedTopics: ['osgi', 'cloud-manager', 'integration-patterns'],
    concerns: [
      'designing a resilient external API integration service',
      'handling mandatory and optional service references',
      'managing typed configuration across environments',
      'protecting secrets and rotating credentials',
      'diagnosing unsatisfied components after deployment',
      'resolving bundle package import and export conflicts',
      'designing scheduled jobs that remain safe during scaling',
      'preventing long-running activation and deactivation logic',
      'implementing timeouts, retries, circuit breakers, and fallback behavior',
      'exposing health, metrics, and operational diagnostics',
      'testing service implementations without coupling to AEM runtime',
      'versioning service interfaces shared across bundles',
      'controlling service ranking and multiple implementations',
    ],
  },
  {
    topic: 'Sling Models',
    category: 'Sling Models',
    topicGroup: 'Development',
    profileTopic: 'Sling Models',
    relatedTopics: ['sling-models', 'htl', 'osgi'],
    concerns: [
      'choosing Resource versus Request adaptables',
      'preventing optional injection from hiding broken content contracts',
      'diagnosing models that adapt on Author but fail on Publish',
      'keeping PostConstruct work lightweight and deterministic',
      'delegating external integrations to OSGi services',
      'building stable Model Exporter contracts',
      'testing injector behavior and adaptation failures',
      'avoiding expensive child-resource traversal during rendering',
      'using Via and resource supertype delegation without hidden coupling',
      'designing models shared across brands and component variants',
    ],
  },
  {
    topic: 'AEM Cloud Service',
    category: 'AEM Cloud Service',
    topicGroup: 'Cloud Service',
    profileTopic: 'AEM Cloud Service',
    relatedTopics: ['aem-cloud-service', 'cloud-manager', 'migration'],
    concerns: [
      'replacing manual production changes with immutable deployments',
      'removing filesystem and local-instance assumptions from legacy code',
      'designing stateless code that remains safe during autoscaling',
      'handling continuous platform updates and release readiness',
      'troubleshooting without direct operating-system access',
      'designing supported repository indexes and configuration changes',
      'migrating content with Content Transfer Tool and validation',
      'using Cloud Manager environment variables and secrets',
      'planning Dispatcher and CDN behavior for cloud delivery',
      'adapting production support runbooks to managed infrastructure',
      'replacing legacy replication assumptions with cloud publication behavior',
      'validating custom workflows and launchers before migration',
      'planning cutover, rollback, and reconciliation for cloud migration',
      'controlling costs through cacheability and efficient integrations',
      'designing observability with centralized logs and environment history',
      'handling development environments and rapid development environments',
      'governing code, configuration, content, and operational ownership',
      'testing compatibility with Cloud Service SDK and quality gates',
      'redesigning scheduled work for dynamic topology',
      'preparing teams for cloud-specific incident response',
    ],
  },
  {
    topic: 'Cloud Manager',
    category: 'Cloud Manager',
    topicGroup: 'Cloud Service',
    profileTopic: 'Cloud Manager',
    relatedTopics: ['cloud-manager', 'testing', 'governance'],
    concerns: [
      'diagnosing code-quality and security gate failures',
      'promoting the same artifact across Dev, Stage, and Production',
      'designing automated smoke and regression tests',
      'handling emergency releases without bypassing governance',
      'managing environment variables and secrets',
      'validating Dispatcher configuration before production',
      'defining production approvals and release evidence',
      'investigating deployments that succeed but degrade the site',
      'coordinating content readiness with application deployments',
      'planning rollback versus forward-fix decisions',
    ],
  },
  {
    topic: 'Security',
    category: 'Security',
    topicGroup: 'Advanced',
    profileTopic: 'Security',
    relatedTopics: ['security', 'service-users', 'dispatcher'],
    concerns: [
      'designing least-privilege service-user access',
      'reviewing custom servlets and endpoints before exposure',
      'protecting against XSS in authored and request-derived content',
      'controlling CORS and CSRF for integrations',
      'preventing sensitive response caching',
      'securing GraphQL and headless delivery endpoints',
      'governing privileged users and production access',
      'managing secrets and credentials across environments',
      'reviewing third-party dependencies and vulnerable libraries',
      'responding to a suspected content or credential breach',
    ],
  },
  {
    topic: 'Performance',
    category: 'Performance Tuning',
    topicGroup: 'Advanced',
    profileTopic: 'Performance',
    relatedTopics: ['performance', 'dispatcher', 'monitoring'],
    concerns: [
      'isolating browser, CDN, Dispatcher, Publish, and integration latency',
      'eliminating traversal queries and inefficient repository access',
      'measuring CDN and Dispatcher cache-hit ratios',
      'profiling slow Sling Models and component rendering',
      'planning campaign traffic load and cache warming',
      'controlling client-library size and execution cost',
      'optimizing DAM renditions and image delivery',
      'setting performance budgets and release gates',
      'handling slow or unavailable external APIs',
      'proving whether autoscaling addresses the real bottleneck',
    ],
  },
  {
    topic: 'Content Fragments',
    category: 'Content Fragments',
    topicGroup: 'Content Management',
    profileTopic: 'Content Fragments',
    relatedTopics: ['content-fragments', 'graphql', 'headless-aem'],
    concerns: [
      'designing stable models for multiple channels',
      'governing schema evolution across API consumers',
      'modelling references without creating deep dependency graphs',
      'planning localization and regional variations',
      'migrating page content into structured fragments',
      'publishing fragments and referenced dependencies',
      'controlling folder permissions and authoring ownership',
      'preventing duplicate and near-identical models',
    ],
  },
  {
    topic: 'GraphQL',
    category: 'GraphQL',
    topicGroup: 'Cloud Service',
    profileTopic: 'GraphQL',
    relatedTopics: ['graphql', 'content-fragments', 'cdn'],
    concerns: [
      'using persisted queries for secure cacheable delivery',
      'controlling query complexity and expensive references',
      'governing schema changes across consumers',
      'debugging missing or stale fields in production',
      'securing endpoints and content permissions',
      'designing CDN caching and invalidation',
      'supporting multiple channels without channel-specific schemas',
      'monitoring API usage, errors, and consumer impact',
    ],
  },
];

const extendedEnterpriseTopics: AemEnterpriseExpansionTopic[] = [
  {
    topic: 'AdaptTo Pattern',
    category: 'AdaptTo Pattern',
    topicGroup: 'Development',
    profileTopic: 'Sling Models',
    relatedTopics: ['adaptto-pattern', 'sling-models', 'resource-resolver'],
    concerns: [
      'choosing the correct adaptable and avoiding request-only assumptions',
      'diagnosing null adaptation on Publish',
      'keeping adapter contracts stable across reusable components',
      'testing adaptation failures and optional dependencies',
      'separating adaptation from expensive business logic',
    ],
  },
  {
    topic: 'Resource Resolver',
    category: 'Resource Resolver',
    topicGroup: 'Advanced',
    profileTopic: 'Security',
    relatedTopics: ['resource-resolver', 'service-users', 'security'],
    concerns: [
      'obtaining least-privilege access for background services',
      'diagnosing resolver leaks and unclosed sessions',
      'handling missing permissions differently from missing content',
      'preventing administrative resolver usage in application code',
      'governing service-user mappings across environments',
    ],
  },
  {
    topic: 'Migration Scenarios',
    category: 'Migration Scenarios',
    topicGroup: 'Architecture',
    profileTopic: 'AEM Cloud Service',
    relatedTopics: ['migration', 'aem-cloud-service', 'upgrade-projects'],
    concerns: [
      'rehearsing content transfer while business publishing continues',
      'replacing unsupported legacy customizations',
      'validating permissions, indexes, and integrations after cutover',
      'planning rollback and reconciliation for a failed migration wave',
      'coordinating code, content, and operating-model readiness',
    ],
  },
  {
    topic: 'Client Libraries',
    category: 'Client Libraries',
    topicGroup: 'Development',
    profileTopic: 'Performance',
    relatedTopics: ['client-libraries', 'performance', 'components'],
    concerns: ['category and dependency design', 'proxy delivery and Dispatcher access', 'site-specific versus shared bundles', 'debugging missing CSS or JavaScript on Publish', 'reducing bundle size and third-party script cost'],
  },
  {
    topic: 'Editable Templates',
    category: 'Editable Templates',
    topicGroup: 'Content Management',
    profileTopic: 'Templates',
    relatedTopics: ['editable-templates', 'content-policies', 'governance'],
    concerns: ['template type ownership and deployment', 'locked structure versus author freedom', 'initial content lifecycle', 'policy inheritance across brands', 'debugging missing allowed components'],
  },
  {
    topic: 'Content Policies',
    category: 'Content Policies',
    topicGroup: 'Content Management',
    profileTopic: 'Templates',
    relatedTopics: ['content-policies', 'templates', 'components'],
    concerns: ['governing component variants across brands', 'preventing policy duplication', 'promoting policies between environments', 'debugging Author and Publish differences', 'managing policy changes without breaking existing pages'],
  },
  {
    topic: 'MSM',
    category: 'MSM',
    topicGroup: 'Content Management',
    profileTopic: 'Architecture',
    relatedTopics: ['msm', 'translation', 'multi-site-manager'],
    concerns: ['blueprint and live-copy ownership', 'rollout configuration design', 'controlling inheritance cancellation', 'localizing shared content safely', 'debugging failed or unexpected rollouts', 'governing large multi-country site estates'],
  },
  {
    topic: 'Workflows',
    category: 'Workflows',
    topicGroup: 'Content Management',
    profileTopic: 'OSGi',
    relatedTopics: ['workflows', 'launches', 'production-support'],
    concerns: ['designing approval workflows without blocking authors', 'preventing workflow launchers from flooding production', 'making custom process steps idempotent', 'handling retries and partial failures', 'monitoring stuck or long-running instances', 'migrating legacy workflows to Cloud Service'],
  },
  {
    topic: 'Query Builder',
    category: 'Query Builder',
    topicGroup: 'Advanced',
    profileTopic: 'JCR',
    relatedTopics: ['query-builder', 'jcr', 'performance'],
    concerns: ['designing indexable predicates', 'reading query plans before production', 'preventing repository traversal', 'supporting pagination and result limits', 'securing queries against unauthorized content', 'debugging slow queries after content growth'],
  },
  {
    topic: 'Service Users',
    category: 'Service Users',
    topicGroup: 'Advanced',
    profileTopic: 'Security',
    relatedTopics: ['service-users', 'security', 'resource-resolver'],
    concerns: ['mapping services to least-privilege identities', 'designing ACLs for shared content', 'replacing administrative sessions', 'debugging permissions that differ by environment', 'reviewing and rotating service access'],
  },
  {
    topic: 'Replication',
    category: 'Replication',
    topicGroup: 'Production Support',
    profileTopic: 'AEM Cloud Service',
    relatedTopics: ['replication', 'publishing', 'production-support'],
    concerns: ['diagnosing blocked publication queues', 'publishing pages with referenced dependencies', 'handling large bulk publications', 'investigating Author and Publish divergence', 'adapting replication assumptions for Cloud Service'],
  },
  {
    topic: 'Launches',
    category: 'Launches',
    topicGroup: 'Content Management',
    profileTopic: 'Templates',
    relatedTopics: ['launches', 'workflows', 'content-governance'],
    concerns: ['planning future campaign content', 'promoting launch changes without losing live edits', 'governing launch ownership and approvals', 'debugging promotion conflicts', 'coordinating launches with application releases'],
  },
  {
    topic: 'Translation',
    category: 'Translation',
    topicGroup: 'Content Management',
    profileTopic: 'Content Fragments',
    relatedTopics: ['translation', 'msm', 'content-fragments'],
    concerns: ['designing translation-project workflows', 'handling translated fragment references', 'coordinating MSM and translation ownership', 'debugging missing or outdated translations', 'governing machine and human translation review'],
  },
  {
    topic: 'DAM',
    category: 'DAM',
    topicGroup: 'Content Management',
    profileTopic: 'Content Fragments',
    relatedTopics: ['dam', 'assets', 'performance'],
    concerns: ['designing metadata schemas and ownership', 'processing high-volume asset ingestion', 'governing asset lifecycle and retention', 'integrating external DAM or PIM systems', 'controlling permissions and sensitive assets', 'monitoring asset-processing failures'],
  },
  {
    topic: 'Assets',
    category: 'Assets',
    topicGroup: 'Content Management',
    profileTopic: 'Performance',
    relatedTopics: ['assets', 'dam', 'cdn'],
    concerns: ['designing responsive renditions', 'optimizing image delivery and cache headers', 'debugging missing renditions', 'handling large video and document assets', 'preventing duplicate assets and broken references'],
  },
  {
    topic: 'Dispatcher Caching',
    category: 'Dispatcher Caching',
    topicGroup: 'Advanced',
    profileTopic: 'Dispatcher',
    relatedTopics: ['dispatcher-caching', 'cdn', 'performance'],
    concerns: ['designing invalidation boundaries', 'handling URL parameters and cache variants', 'caching pages with referenced fragments', 'preventing private response caching', 'measuring and improving cache-hit ratio', 'debugging stale content across cache layers'],
  },
  {
    topic: 'Apache Configuration',
    category: 'Apache Configuration',
    topicGroup: 'Advanced',
    profileTopic: 'Dispatcher',
    relatedTopics: ['apache', 'dispatcher', 'security'],
    concerns: ['designing vhosts and domain routing', 'implementing redirects without loops', 'controlling security headers', 'debugging rewrite-rule precedence', 'promoting configuration through Cloud Manager'],
  },
  {
    topic: 'CDN',
    category: 'CDN',
    topicGroup: 'Advanced',
    profileTopic: 'Dispatcher',
    relatedTopics: ['cdn', 'dispatcher', 'performance'],
    concerns: ['designing cache-control and TTL strategy', 'invalidating edge content safely', 'debugging CDN versus Dispatcher staleness', 'protecting personalized and authenticated responses', 'measuring edge performance and cache effectiveness'],
  },
  {
    topic: 'SEO in AEM',
    category: 'SEO in AEM',
    topicGroup: 'Development',
    profileTopic: 'Components',
    relatedTopics: ['seo', 'components', 'multi-site'],
    concerns: ['governing canonical URLs across domains', 'generating sitemaps at enterprise scale', 'handling redirects and URL migrations', 'managing structured data through components', 'preventing localization and MSM duplicate-content issues'],
  },
  {
    topic: 'Accessibility',
    category: 'Accessibility',
    topicGroup: 'Development',
    profileTopic: 'Components',
    relatedTopics: ['accessibility', 'components', 'testing'],
    concerns: ['building accessible component contracts', 'preventing author configuration from breaking accessibility', 'testing keyboard and screen-reader behavior', 'governing WCAG compliance across brands', 'handling accessibility defects in shared components'],
  },
  {
    topic: 'Testing',
    category: 'Testing',
    topicGroup: 'Development',
    profileTopic: 'Cloud Manager',
    relatedTopics: ['testing', 'cloud-manager', 'components'],
    concerns: ['testing Sling Models and OSGi services', 'writing integration tests for AEM endpoints', 'validating Dispatcher and CDN behavior', 'building authoring regression coverage', 'designing production smoke tests', 'using quality gates without brittle test suites'],
  },
  {
    topic: 'Integration Patterns',
    category: 'Integration Patterns',
    topicGroup: 'Architecture',
    profileTopic: 'OSGi',
    relatedTopics: ['integrations', 'osgi', 'architecture'],
    concerns: ['choosing synchronous versus asynchronous integration', 'handling retries and idempotency', 'isolating vendor APIs behind stable services', 'protecting credentials and customer data', 'monitoring and degrading gracefully when dependencies fail', 'governing integration contracts and ownership'],
  },
  {
    topic: 'Headless AEM',
    category: 'Headless AEM',
    topicGroup: 'Architecture',
    profileTopic: 'GraphQL',
    relatedTopics: ['headless-aem', 'graphql', 'content-fragments'],
    concerns: ['deciding headless versus page delivery', 'designing stable omnichannel content models', 'governing API schema evolution', 'caching persisted queries at the edge', 'securing consumer access', 'operating hybrid headless and page-based sites'],
  },
  {
    topic: 'Multi Site Manager',
    category: 'Multi Site Manager',
    topicGroup: 'Architecture',
    profileTopic: 'Architecture',
    relatedTopics: ['multi-site-manager', 'msm', 'translation'],
    concerns: ['selecting blueprint boundaries', 'governing rollout ownership across markets', 'controlling inherited and local content', 'coordinating translation and rollout', 'reducing operational risk across hundreds of sites'],
  },
  {
    topic: 'Multi Brand Architecture',
    category: 'Multi Brand Architecture',
    topicGroup: 'Architecture',
    profileTopic: 'Architecture',
    relatedTopics: ['multi-brand', 'components', 'governance'],
    concerns: ['sharing components without coupling brand releases', 'using policies and design tokens for variation', 'separating brand content and permissions', 'governing shared-platform ownership', 'preventing duplicated code and templates', 'measuring platform cost and reuse'],
  },
  {
    topic: 'Multi Region Architecture',
    category: 'Multi Region Architecture',
    topicGroup: 'Architecture',
    profileTopic: 'Architecture',
    relatedTopics: ['multi-region', 'cdn', 'aem-cloud-service'],
    concerns: ['meeting regional latency expectations', 'handling data residency and privacy', 'designing regional failover expectations', 'coordinating content publication globally', 'operating integrations with regional dependencies', 'defining realistic disaster-recovery objectives'],
  },
  {
    topic: 'Migration',
    category: 'Migration',
    topicGroup: 'Architecture',
    profileTopic: 'AEM Cloud Service',
    relatedTopics: ['migration', 'aem-cloud-service', 'governance'],
    concerns: ['assessing legacy compatibility and technical debt', 'planning content transformation and validation', 'migrating custom indexes and permissions', 'rehearsing cutover and rollback', 'coordinating code and content migration streams', 'measuring migration completeness and reconciliation'],
  },
  {
    topic: 'Upgrade Projects',
    category: 'Upgrade Projects',
    topicGroup: 'Architecture',
    profileTopic: 'AEM Cloud Service',
    relatedTopics: ['upgrade', 'migration', 'testing'],
    concerns: ['assessing deprecated APIs and customizations', 'upgrading Core Components and dependencies', 'validating content and authoring compatibility', 'planning regression and performance testing', 'sequencing upgrade releases with business delivery'],
  },
  {
    topic: 'Production Support',
    category: 'Production Support',
    topicGroup: 'Production Support',
    profileTopic: 'Performance',
    relatedTopics: ['production-support', 'monitoring', 'troubleshooting'],
    concerns: ['triaging a live-site outage', 'handling content published but not visible', 'investigating sudden performance degradation', 'coordinating incident ownership across teams', 'creating safe remediation and rollback plans', 'writing runbooks from repeated incidents'],
  },
  {
    topic: 'Troubleshooting',
    category: 'Troubleshooting',
    topicGroup: 'Production Support',
    profileTopic: 'Performance',
    relatedTopics: ['troubleshooting', 'logging', 'monitoring'],
    concerns: ['isolating Author, Publish, Dispatcher, CDN, and browser layers', 'correlating failures with deployments and content changes', 'preserving evidence before remediation', 'reproducing intermittent production failures', 'validating targeted fixes and preventing recurrence'],
  },
  {
    topic: 'Monitoring',
    category: 'Monitoring',
    topicGroup: 'Production Support',
    profileTopic: 'Performance',
    relatedTopics: ['monitoring', 'logging', 'cloud-manager'],
    concerns: ['defining user-impact service indicators', 'monitoring publication and cache health', 'alerting on integration degradation', 'avoiding noisy non-actionable alerts', 'correlating metrics with releases and incidents'],
  },
  {
    topic: 'Logging',
    category: 'Logging',
    topicGroup: 'Production Support',
    profileTopic: 'AEM Cloud Service',
    relatedTopics: ['logging', 'monitoring', 'security'],
    concerns: ['designing actionable structured logs', 'protecting personal and secret data', 'correlating requests across services', 'controlling log volume and cost', 'using centralized Cloud Service logs during incidents'],
  },
  {
    topic: 'Governance',
    category: 'Governance',
    topicGroup: 'Architecture',
    profileTopic: 'Architecture',
    relatedTopics: ['governance', 'security', 'multi-brand'],
    concerns: ['defining ownership for shared platform capabilities', 'governing component and content-model lifecycle', 'reviewing architecture decisions and exceptions', 'controlling release and production access', 'measuring reuse, quality, cost, and operational health', 'retiring legacy capabilities safely'],
  },
];

function expandTopic(topic: AemEnterpriseExpansionTopic): AemEnterpriseQuestionSeed[] {
  return topic.concerns.flatMap((concern) => [
    {
      topic: topic.topic,
      category: topic.category,
      topicGroup: topic.topicGroup,
      profileTopic: topic.profileTopic,
      relatedTopics: topic.relatedTopics,
      question: `How would you handle ${concern} in an enterprise ${topic.topic} implementation? Explain the trade-offs, governance, and Cloud Service implications.`,
    },
    {
      topic: topic.topic,
      category: topic.category,
      topicGroup: topic.topicGroup,
      profileTopic: topic.profileTopic,
      relatedTopics: topic.relatedTopics,
      question: `A production incident exposes a weakness in ${concern}. How would you diagnose the ${topic.topic} issue, identify evidence, and prevent recurrence?`,
    },
  ]);
}

export const aemEnterpriseQuestionSeeds: AemEnterpriseQuestionSeed[] = [
  ...coreExpansionTopics.flatMap(expandTopic),
  ...extendedEnterpriseTopics.flatMap(expandTopic),
];
